on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 4'

name: Test

jobs:
  docker:
    name: Docker
    runs-on: macos-13
    steps:
      - uses: mxschmitt/action-tmate@master
